language: r
r: bioc-devel
r_github_packages: 
    - github::computational-metabolomics/pmp
cache: 
  packages: true
sudo: required
warnings_are_errors: false
dist: trusty
after_success:
    - Rscript -e 'covr::codecov()'
